### ISSUE TITLE
Slow wifi connections time out and go into AP mode

### ISSUE THREAD

**Issue by bmidgley** [bmidgley/citizen-scientist#25]
If the wifi connection takes a long time or is unreliable, the device goes into AP mode. Combined with reset cycles causes the device to be unreliable.

There should be a way to lock the wifi or make a long timeout.

I think I'd prefer a configuration option to lock the wifi and never enter AP mode.

If the wifi is locked in via flash memory options, then the program button would be required to reset the wifi and get back into AP mode. This will have to work either when associated or when trying to get associated. 

I'm not sure we can get into the wifimanager loop, but we could execute this using a connect timeout combined with a test for the button press if you don't mind holding the button for a while to reset it.

**Comment by timcharper** [comment]
I don't think my wifi is unreliable :) I'm not sure why the ESP8266 device reboots occasionally, seems it is just a feature of them :)

**Comment by bmidgley** [comment]
It didn't always reboot so often. One of the library updates did this, but I prefer reboot to crash. :/

**Comment by timcharper** [comment]
Hmm... I'll monitor the serial for a night and see if I can catch the crash. There might be some stack trace info that will help us pinpoint where it's failing.

I've noticed that really-fast-loops cause the device to crash. Not sure why. `while(1) {}` will crash the device but `while(1) { delay(25); }` will run forever.

**Comment by timcharper** [comment]
@bmidgley what would you think if we worked around it? We could have our own code check to see if an AP is persisted, first, and then try and connect to it if so, and then breaking out of the loop in to AP mode if the button is pressed.

For the meantime, I think it seems reasonable to take the case apart and reset if changing AP's; that's not a frequent occurrence. Further we could expose an endpoint which, when hit, reboots the device in AP / config mode.

**Comment by timcharper** [comment]
#29 addresses this
